### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by behailu2021** [behailu2021/weather-app-2022#1]
- [  ]  create GitHub repo
-  [ ]  create initial project & push to repo (setup with Vite, Prettier, ESLint)
- [  ]  Register for a free[ OpenWeatherMap](http://api.openweathermap.org/) API key(s)
- [  ]  Build form
- [ ]  Build logic to call weather API from the form to get weather data
- [  ]  Build logic to call the maps API to get aerial shot
- [  ]  Research API that can solve this
- [  ]  Build logic to display weather resu

**Comment by DavidScales** [comment]
this was just a test issue. closing
