### ISSUE TITLE
Build logic for calling weather API

### ISSUE THREAD

**Issue by DavidScales** [behailu2021/weather-app-2022#7]
Write a function that  that accepts either city or zip code, and gets weather data for that location using the weather api https://openweathermap.org/api. The function should return the JSON from the API.

Once you have done this, you can create a pull request if you are up to it. See "How to get started collaborating in GitHub" in our team doc https://docs.google.com/document/d/14xlY16gBX8gMoJEg5FayYJzFfWpr3EccKfXmonfPf20/r/0-gbTdcLbcD4TBnbUa1yhAmg/edit#heading=h.cymq2gg5ldjq

### Tips
* You'll need to sign up for an API key

**Comment by DavidScales** [comment]
so this might look like (as an example):
```
const weatherData = getWeatherForLocation('Seattle')
console.log(weatherData) // { temperature: 65, humidity: 80, condition: 'cloudy' }
```

**Comment by Haxagonus** [comment]
I have the local code that converts text input into latitude and
longitude and returns weather data for us to use but I don't think I have
access to the repo so maybe on Monday you guys can give me that so I can
push my code.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/30/22,
09:29:01 PM

**Comment by behailu2021** [comment]
I just resent the invitation to you.
